### PR TITLE
style source_sets#index

### PR DESCRIPTION
**Pull request by AudreyAltman**
This styles `source_sets#index`.

### CODE REVIEW

**Comment by AudreyAltman** [comment]
I should note that all the `featured_image`s (ie "small" images) are the same height and width dimensions, and they are slightly larger than the largest possible zoom in this layout, so it should look good.

**Comment by AudreyAltman** [comment]
rebased to develop

**Comment by AudreyAltman** [comment]
A caveat to my earlier comment about the images looking good in the layout - they are a off-center in the mobile view, but I think this is something we can fix next week.

**Comment by markbreedlove** [comment]
I'm forget how the thumbnails or small images are supposed to bubble up to the set list, but it's probably OK if you've tested it.  I have an index page without any thumbnails, but I can't find where to assign a thumbnail for the set itself.

**Comment by AudreyAltman** [comment]
You have to assign a "small" image to a source, and then mark that source as "featured".  Then the set that is the parent of that source will use the "small" image on this page. But yes, I've tested it.

**Comment by markbreedlove** [comment]
ok

**Pull request merged**
