### PR TITLE
Feature/primary source set

### PR DESCRIPTION
**Pull request by AudreyAltman**
This PR introduces a basic CRUD interface for primary source sets.

Additional changes:
Get set up for rspec testing.
Remove assets group from Gemfile b/c it is not supported in more recent versions of Rails
Remove some unnecessary directories and files.

Still to do (in subsequent PRs):
Add media upload capability.
Add CRUD interfaces for other models.

### CODE REVIEW

**Comment by no-reply** [comment]
Since a couple of the changes in this PR are now mine, I want to throw it back to @AudreyAltman for a :+1: before merging.

I'm aware that there were some problems with the automation side of this, and it wasn't clear to me whether the fix would be on this end or there. Either way, this is now passing CI, so I think we should consider it in a healthy state. If there's something wrong with the setup, it can be handled in another PR.

**Comment by AudreyAltman** [comment]
:+1: I think this is good to go.  I will :squash:

**Comment by AudreyAltman** [comment]
Okay, I :squash:ed to 3 commits.  Ready to :merge: @no-reply approves.

**Comment by no-reply** [comment]
:rocket:

**Pull request merged**
