### PR TITLE
Enable test coverage with simplecov

### PR DESCRIPTION
**Pull request by markbreedlove**
Add coverage reports.

### CODE REVIEW

**Comment by AudreyAltman** [comment]
Don't we also need to add `simplecov` to the `Gemfile`?

**Comment by markbreedlove** [comment]
It's already in my Gemfile.lock, probably by virtue of being required by something else.

**Comment by markbreedlove** [comment]
Apparently by `codeclimate-test-reporter`

**Comment by AudreyAltman** [comment]
Ah!  In that case, I think this is good to go.

**Pull request merged**
