### PR TITLE
style teaching guide

### PR DESCRIPTION
**Pull request by AudreyAltman**
This introduces CSS styling for a guide.

### CODE REVIEW

**Comment by markbreedlove** [comment]
If there could be a style for `.primary-source-sets .moduleSection a` after [this point](https://github.com/dpla/primary-source-sets/blob/feature/guide-style/app/assets/stylesheets/primary_source_sets.css#L12-L14), then it would keep the anchor links from wrapping:
```
white-spece: nowrap;
```
If you want to take a minute to do that.  If not, this is fine; happy to merge it.

**Comment by AudreyAltman** [comment]
@markbreedlove which anchor links are you thinking that we should keep from wrapping?  Some of the links in the modules are longer than the width of a line, so I think we need to wrap them.

**Comment by AudreyAltman** [comment]
I am going to change the hard-coded email address in this view as well.

**Comment by markbreedlove** [comment]
In that case, this can be revisited later.

**Comment by markbreedlove** [comment]
I was thinking the link in the box that says "Primary Source Set" in the upper-right.

**Comment by AudreyAltman** [comment]
Oh yeah, some of those Primary Source Set names are super long.

**Comment by AudreyAltman** [comment]
Okay, I changed the previously hard-coded [email](https://github.com/dpla/primary-source-sets/commit/8078eea05f53f38ae689679d6c07fa8723d35e00#diff-d18bc7e6b81d90f582b475cfa9d0c18aR90).  I also added some [conditional statements](https://github.com/dpla/primary-source-sets/commit/8078eea05f53f38ae689679d6c07fa8723d35e00#diff-d18bc7e6b81d90f582b475cfa9d0c18aR30) so that "questions" and "activity" only display if they are present.  I tested both changes in my browser.

**Comment by markbreedlove** [comment]
:+1:

**Pull request merged**
