### PR TITLE
Refactor Javascript and add tests

### PR DESCRIPTION
**Pull request by markbreedlove**
Addresses https://issues.dp.la/issues/8075

* Refactor upload-related Javascript, creating UploadHandler, AVUploadHandler, DocUploadHandler, and ImageUploadHandler functions, reducing redundancy and allowing unit testing.
* Add `id` attribute to upload forms so that they are distinguishable from search forms that were recently added to the layout.
* Add Jasmine tests for Javascript code.
* Update Vagrantfile so that you can view Jasmine tests on http://localhost:3001/

### CODE REVIEW

**Comment by markbreedlove** [comment]
I should have mentioned this, but you'll need to run `vagrant provision` for the development VM to install a package it will need to allow the phantom-js gem to be installed.

**Comment by markbreedlove** [comment]
I should also have added some quick notes about Jasmine.

To run the tests in with output to the console, you do `bundle exec rake jasmine:ci` the same as you'd do `rake ci`.  To run a Webrick server on port 3001, do `bundle exec rake jasmine`, and then go to `http://localhost:3001/` in your browser. Whenever you reload the page the tests are run again.  You can do that while you're developing, with the regular rails server running in another shell on port 3000.

**Comment by AudreyAltman** [comment]
This is AWESOME.  I am so excited to have Jasmine up and running.  I like what you've done with the `UploadHander` prototype - it makes things nice and clean.

I tested this in my browser by uploading a bunch of media, and it seems to be working great.  I think its ready to :merge:

**Comment by markbreedlove** [comment]
Great!  Glad you like it.

**Pull request merged**
