### PR TITLE
Feature/optimize db calls

### PR DESCRIPTION
**Pull request by AudreyAltman**
This optimizes calls to the database by refactoring to reduce the total number of database calls, and eager loading objects with `includes`.  I hope that it will reduce page load time.  

This has been tested locally.  It addresses [#8259](https://issues.dp.la/issues/8259).

### CODE REVIEW

**Comment by moltude** [comment]
@AudreyAltman  I've done some reading on includes/joins and I think this looks good. I haven't done any performance testing locally. Do you think we should do performance testing between staging and production before merging into develop?

**Comment by AudreyAltman** [comment]
@moltude good suggestion.  I'll look into some options for doing performance testing.

**Comment by AudreyAltman** [comment]
@moltude: I haven't yet found a good way to do automated performance testing, so I did some light ad-hoc testing.  Based on a small set of trials on staging, time spent communicating with the database was reduced by 16% on `source_sets/index`, 7% on `source_set/show`, and 5% on `source/show`.  This should scale favorably in production, where there is more data to process.  

Also, I rebased to develop.

**Comment by AudreyAltman** [comment]
I also took some baseline measurements on production, so we can see how it's performing after this is deployed.

**Comment by AudreyAltman** [comment]
I found a bug in this, so please hold off merging until I can fix it!

**Comment by AudreyAltman** [comment]
@moltude: The bug is fixed, and here’s a summary of all the changes:

It turns out I can’t preload (i.e. include) `tags` in the `source_set` `index` call.  Sometimes, the index needs to display _only sets having specified tags_.  In these cases, the query will _only_ load the specified tags, as opposed to _all_ tags belonging to a set.  This defeats the purpose of the preload, as the view will need to display all of the tags.  This is unfortunate because it means that the app will need to send an additional query for each set in order to get all the tags, but I will just have to try and optimize this with caching.

I did refactor the db call that gets all the tags for the set.  There is a caveat - we really only want tags that are associated with vocabularies for which the value of `filter` is `true`.  Before I was getting all the tags from the database, and then doing some convoluted view logic to get the tags associated with filterable vocabs. I replaced this with model methods.  See https://github.com/dpla/primary-source-sets/pull/165/commits/b78484953b951b4503162a883cf3e84c1f874a79#diff-8aea8a5bfdb4698272ac5b9ee26ba88fR9 and https://github.com/dpla/primary-source-sets/pull/165/commits/b78484953b951b4503162a883cf3e84c1f874a79#diff-8fe92870a7f027a46eed82a51c5c16bcR18  There’s a couple new associated specs tests for the models.  The view logic I replaced is in `app/views/source_sets/_set_tile.html.erb`, and also I no longer need to pass the `filter` variable between view partials.

I also refactored the method `self.with_tags` in `app/models/source_set.rb` so that it’s only one call to the database, rather than one call per tag.  This has the added benefit of causing this method to return an `ActiveModel::Relation` instead of an `Array`, which makes it easier to combine with other methods.  I did, however, need to change the views to work `ActiveModel::Relation` by calling `length` instead of `count` to get the total number of sets returned by the query.

I think that covers the new changes.  I’ve tested it locally, and it seems to be working fine.  I will squash the two commits before merge, but I wanted to leave them separate for the time being for ease of code review.

**Comment by AudreyAltman** [comment]
Just added one last thing - a correction in the `source` `show` view so that it only shows filterable tags, as opposed to all tags.  Tested locally.

**Comment by AudreyAltman** [comment]
ER-Diagram for reference: https://digitalpubliclibraryofamerica.atlassian.net/wiki/display/TECH/Relational+Database+Model

**Comment by AudreyAltman** [comment]
@moltude squashed, rebased, and ready to merge

**Comment by moltude** [comment]
👍

**Pull request merged**
